export const SCHEDULE_ACCESS_ERROR_CODES = {
  AUTHENTICATION_REQUIRED: "AUTHENTICATION_REQUIRED",
  AUTHORIZATION_FAILED: "AUTHORIZATION_FAILED",
  UNAVAILABLE_DENIED: "UNAVAILABLE_DENIED",
  SCHEDULE_NOT_PUBLISHED: "SCHEDULE_NOT_PUBLISHED",
  OPERATIONAL_FAILURE: "OPERATIONAL_FAILURE",
  TLS_REQUIRED: "TLS_REQUIRED"
} as const;

export type ScheduleAccessErrorCode =
  (typeof SCHEDULE_ACCESS_ERROR_CODES)[keyof typeof SCHEDULE_ACCESS_ERROR_CODES];
