export const REFEREE_ACCESS_OUTCOMES = {
  ASSIGNMENTS_AVAILABLE: "ASSIGNMENTS_AVAILABLE",
  NO_ASSIGNMENTS: "NO_ASSIGNMENTS",
  ACCESS_GRANTED: "ACCESS_GRANTED",
  UNAVAILABLE: "UNAVAILABLE",
  UNAVAILABLE_OR_NOT_FOUND: "UNAVAILABLE_OR_NOT_FOUND",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  INTERNAL_ERROR: "INTERNAL_ERROR"
} as const;

export type RefereeAccessOutcomeCode =
  (typeof REFEREE_ACCESS_OUTCOMES)[keyof typeof REFEREE_ACCESS_OUTCOMES];
